quarkus:
  datasource:
    db-kind: h2
    username: acme
    password: x1dasj1
    jdbc:
      driver: org.h2.Driver
      url: jdbc:h2:./data/api
  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script: import.sql
    log:
      sql: true
  swagger-ui:
    always-include: true
mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: ${project.name}
          description: ${project.description}
          version: ${project.version}